### ISSUE TITLE
You might've logged the credentials of whoever has used this

### ISSUE THREAD

**Issue by Chiroyce1** [Nicest-One/scratchon#4]
> **@Nicest-One:** I don't store any of your Scratch credentials, anywhere. I am not lying here, but if you feel unsafe and have used scratchon, you can reset your scratch password at anytime.

You can't be 100% sure that you never stored it
<img width="747" alt="image" src="https://user-images.githubusercontent.com/97374054/185608173-e78a5132-6141-4835-ada0-c2352d8a1750.png">

**Comment by Nicest-One** [comment]
I just deleted all the versions of scratchon that used the authentication website. (the website on heroku) I'm not lying, I did not store any data, I just wanted to help solve the Replit issue, yet it went wrong.

**Comment by Nicest-One** [comment]
Even if I did have users credentials, (which I dont) I would never think of doing anything harmful. The only reason I took this approach of hosting a server on heroku, was because I wanted to fix the Replit issue for the scratch API. I really didn't consider people thinking that this is unsafe, as I just wanted to help.
